# Generated by Django 3.2.8 on 2021-10-26 21:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.png', help_text='Ensure your picture dimension is 300x300 in px ~Iykeln :)', upload_to='document/')),
                ('address', models.CharField(max_length=42, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid address', message='Enter a valid ethereum address', regex='^0x[a-fA-F0-9]{40}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
